-- Simplified schema for manual execution in Supabase SQL editor.
-- Intentionally no RLS, no Supabase Auth dependency, and plain text passwords.

-- Remove old objects from initial schema if they exist.
drop function if exists public.is_team_owner(bigint);

drop table if exists public.lineups_bb cascade;
drop table if exists public.games_bb cascade;
drop table if exists public.rules_bb cascade;
drop table if exists public.players_bb cascade;
drop table if exists public.teams_bb cascade;

-- Users (plain text password by request).
create table if not exists public.users_bb (
  id int generated always as identity primary key,
  email text not null unique,
  password text not null check (length(password) > 0),
  created_at timestamptz not null default now()
);

-- Team root entity.
create table if not exists public.teams_bb (
  id int generated always as identity primary key,
  user_id int not null references public.users_bb (id) on delete cascade,
  name text not null,
  logo_url text,
  created_at timestamptz not null default now()
);

-- Roster with flexible position data kept as JSONB for simplicity.
create table if not exists public.players_bb (
  id int generated always as identity primary key,
  team_id int not null references public.teams_bb (id) on delete cascade,
  name text not null,
  positions jsonb not null default '{}'::jsonb,
  flexibility_level text not null check (flexibility_level in ('starter', 'absent')),
  excluded_positions jsonb not null default '[]'::jsonb,
  locked_position text check (locked_position in ('P', 'C', '1B', '2B', '3B', 'SS', 'LF', 'CF', 'RF')),
  locked_can_bench boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Team rules / game configuration snapshot.
create table if not exists public.rules_bb (
  id int generated always as identity primary key,
  team_id int not null references public.teams_bb (id) on delete cascade,
  innings_count int not null default 6 check (innings_count between 1 and 12),
  pitcher_id int references public.players_bb (id) on delete set null,
  max_pitcher_innings int not null default 5,
  pitcher_changes jsonb not null default '{}'::jsonb,
  fixed_center_field boolean not null default false,
  fixed_center_field_player_id int references public.players_bb (id) on delete set null,
  fixed_assignments jsonb not null default '[]'::jsonb,
  prioritize_catcher boolean not null default true,
  max_consecutive_bench int not null default 2,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Saved lineup history snapshots generated by the app.
create table if not exists public.match_history_bb (
  id int generated always as identity primary key,
  team_id int not null references public.teams_bb (id) on delete cascade,
  label text not null,
  lineup_json jsonb not null,
  bench_totals jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_teams_bb_user_id on public.teams_bb (user_id);
create index if not exists idx_players_bb_team_id on public.players_bb (team_id);
create index if not exists idx_rules_bb_team_id on public.rules_bb (team_id);
create index if not exists idx_match_history_bb_team_id on public.match_history_bb (team_id);
create index if not exists idx_match_history_bb_created_at on public.match_history_bb (created_at desc);