-- Extra columns to support frontend state import/sync.
-- Run manually in Supabase SQL editor.

alter table if exists public.players_bb
  alter column id set generated by default;

alter table if exists public.rules_bb
  add column if not exists manual_overrides jsonb not null default '{}'::jsonb,
  add column if not exists locked_overrides jsonb not null default '[]'::jsonb,
  add column if not exists selected_history_match_id text,
  add column if not exists history_context_window int not null default 1,
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.rules_bb
  drop constraint if exists rules_bb_history_context_window_check;

alter table if exists public.rules_bb
  add constraint rules_bb_history_context_window_check
  check (history_context_window between 1 and 3);

alter table if exists public.match_history_bb
  add column if not exists client_match_id text;

create unique index if not exists uq_match_history_bb_team_client
  on public.match_history_bb (team_id, client_match_id);
